### ISSUE TITLE
TrackPlayer error

### ISSUE THREAD

**Issue by npk7264** [Trinhtruc1831/NT118.M22_AndroidMusicApp#3]
Em cũng đang code app nhạc ạ, nhưng mà import TrackPlayer thì bị như này: TypeError: null is not an object (evaluating 'TrackPlayer.RATING_HEART'). Ac có gặp trường hợp này chưa support e với ạ (e code với expo go)

**Comment by Trinhtruc1831** [comment]
> Em cũng đang code app nhạc ạ, nhưng mà import TrackPlayer thì bị như này: TypeError: null is not an object (evaluating 'TrackPlayer.RATING_HEART'). Ac có gặp trường hợp này chưa support e với ạ (e code với expo go)

Issue này hồi trước mình cũng có gặp lúc import TrackPlayer này. Khá tiếc là đồ án này cũng lâu quá rồi nên mình không nhớ cụ thể cách mình giải quyết như thế nào, nhưng đại ý là cài đặt TrackPlayer với expo go khác với react-native bình thường, phải cài đặt thêm môi trường nữa, cụ thể là phần dưới cùng của TrackPlayer có hướng dẫn, bạn tham khảo [ở đây](https://react-native-track-player.js.org/docs/basics/installation#expo) nha.

Nếu vẫn không được thì bạn tham khảo tiếp [issue này](https://github.com/doublesymmetry/react-native-track-player/issues/1504) nha, tại trong bookmark của mình có lưu lại trong quá trình thực hiện đồ án nên mình nghĩ là mình có dùng đến.

Thêm một lưu ý nhỏ, mình không biết bạn có cần tới không, thì lúc mình làm đồ án có tìm hiểu được là vẫn còn một package khác có hỗ trợ, dễ cài đặt và hình như là được xây dựng riêng cho expo go là expo-av. Để so sánh thì ngoài các chức năng bth là loop suffle này kia thì expo-av có thể play hai đối tượng nhạc cùng một lúc, trong khi đó thì TrackPlayer chỉ cho play một state nhạc duy nhất. Tuy nhiên theo mình nhớ là trackplayer theo dõi được cái thanh điều khiển nhạc, tức là kéo qua kéo lại thì nhạc mình có thể đến đúng vị trí play theo người dùng mong muốn. Mà do app mình lúc làm đồ án cần cả hai chức năng play nhạc tuy chỉnh và mix nhạc nên đã cài đặt cả hai package đó. NHƯNG, cho đến thời điểm báo cáo thì mình vẫn phải tách hai chức năng đó thành hai resource khác nhau để báo cáo vì hai package này bị conflict với nhau.

Tái bút: Phản hồi này chỉ mang tính chất là tường thuật lại trải nghiệm khi mình thực hiện đồ án, nên còn hơi dài dòng, mặt khác, so với thời điểm hiện tại thì các tính năng, package, các mô tả của mình đôi khi đã khác. Cho nên, mình rất lấy làm tiếc vì có thể vẫn chưa giúp bạn giải quyết được vấn đề. Cuối cùng, chúc bạn fix được bug và hoàn thiện tốt đồ án của mình nhen.

**Comment by npk7264** [comment]
Dạ e cảm ơn ạ, chị support nhiệt tình quá, e cũng là dân UIT ^^
